name: Docker Image CI

on:
  push:
    branches: "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/imghabbats:latest
      - name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker stop ${{ secrets.CNAME }}
            sudo docker rm ${{ secrets.CNAME }}
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/imghabbats
            sudo docker run --name ${{ secrets.CNAME }} -p 80:8000 -d -e DB_HOST=${{secrets.DB_HOST}} -e DB_PORT=${{secrets.DB_PORT}} -e DB_USER=${{secrets.DB_USER}} -e DB_NAME=${{secrets.DB_NAME}} -e DB_PASS=${{secrets.DB_PASS}} -e SECRET=${{secrets.JWTSECRET}} -e REFSECRET=${{secrets.REFSECRET}} -e CDN_CLOUD_NAME=${{secrets.CDN_CLOUD_NAME}} -e CDN_API_KEY=${{secrets.CDN_API_KEY}} -e CDN_API_SECRET=${{secrets.CDN_API_SECRET}} -e CDN_FOLDER_ARTICLES=${{secrets.CDN_FOLDER_ARTICLES}} -e CDN_FOLDER_COURSE=${{secrets.CDN_FOLDER_COURSE}} -e SERVER_PORT=${{secrets.SERVER_PORT}} -e MONGO_URI=${{secrets.MONGO_URI}} -e MONGO_DB_NAME=${{secrets.MONGO_DB_NAME}} -e OPENAI_KEY=${{secrets.OPENAI_KEY}} ${{ secrets.DOCKERHUB_USERNAME }}/imghabbats
